name: flightbooker-backend deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ docker ]
    paths:
    - 'FlightBooker/flightbooker-backend/**'
    - '.github/workflows/build-deploy-backend.yaml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: flightbookeracr.azurecr.io
          username: ${{ secrets.FLIGHTBOOKER_REGISTRY_USERNAME }}
          password: ${{ secrets.FLIGHTBOOKER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: flightbookeracr.azurecr.io/flightbookerbackend:${{ github.sha }} , flightbookeracr.azurecr.io/flightbookerbackend:latest
          file: FlightBooker/flightbooker-backend/Dockerfile
          context: ./.
